server:
  port: 6666
#eureka config#
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.112:1111/eureka
  instance:
    appname: ${spring.application.name}
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true
spring:
  application:
    name: call-service