server:
  port: 1111

#eureka config#
eureka:
  instance:
    appname: ly-eureka-server
  client:
    fetch-registry: false
    register-with-eureka: false
#    service-url: http://127.0.0.1:1111/eureka

#spring config#
spring:
  application:
    name: id-generator